### ISSUE TITLE
Coveralls spamming

### ISSUE THREAD

**Issue by Jean85** [phpcommunity/phptestfest.org#13]
Can we please disable the automatic reply from Coveralls? The response in the check below each PR is enough I think, we are getting spammed, see #12

**Comment by ramsey** [comment]
I think this is a result of the different jobs (5.6, 7.0, 7.1) on Travis all reporting separately to Coveralls. I'll look into disabling the PR comments from Coveralls.

**Comment by ramsey** [comment]
I think these settings will disable the PR comments. We'll see the next time a PR is created. 

Thanks for reporting this!

<img width="625" alt="coveralls_-_test_coverage_history___statistics" src="https://user-images.githubusercontent.com/42941/27978141-8bad7c5c-6333-11e7-9868-e81b4ce440fa.png">
