### ISSUE TITLE
Create command phpt:skeleton for ./bin/testfest

### ISSUE THREAD

**Issue by rogeriopradoj** [phpcommunity/phptestfest.org#14]
At this moment, if you install and run https://packagist.org/packages/phpc/testfest you see that there's a command there named `phpt:skeleton`, but it's not implemented yet.

It would be fine if it create a complete `.phpt` file from scratch as a template, then the users could start to write their own tests on top of that generated file.

As a starting point, we have lots of examples on <https://phptestfest.org/resources/>.

**Comment by Jean85** [comment]
Can you please elaborate a bit on the subject?

**Comment by rogeriopradoj** [comment]
Hi, @Jean85 , I just updated issue description. Thanks!

**Comment by rogeriopradoj** [comment]
I think we could borrow a command that is already available on php/php-src:
- https://wiki.php.net/qa/phptlessonslearned#test_case_generator
- https://github.com/php/php-src/tree/master/scripts/dev/generate-phpt

@phpcommunity/testfest @Jean85 what do you think?

**Comment by ramsey** [comment]
This sounds good to me.

**Comment by ghost** [comment]
@rogeriopradoj @ramsey I was working to integrate the `generate-phpt.phar` from the `php-src` into `docker-phpqa` and just finished.

If you have time take a look at: https://github.com/herdphp/docker-phpqa/pull/25

Basically now phpqa has two main commands. For example:

`phpqa generate /path/to/phpt -f ucfirst -b` generates the file `ucfirst_basic.phpt`, which is a PHPT template file with the necessary boilerplate code to create a basic test for the `ucfirst` php function.

`phpqa run /path/to/phpt/ucfirst_basic.phpt 72` will run the test in PHP 7.2.0alpha1. 

=)
