### ISSUE TITLE
Use Github pages for website

### ISSUE THREAD

**Issue by emirb** [phpcommunity/phptestfest.org#5]
Currently https://phptestfest.org/ is showing only a placeholder.

It would make sense to have it hosted in this repo, with separated `gh-pages` branch, containing basic info and communication channels (IRC, Slack links, etc) and link to Github repository itself.

**Comment by ramsey** [comment]
It is hosted in this repo in the `docs/` directory. I’m currently working on it. :-)

**Comment by ramsey** [comment]
Website published from `docs/` directory and instructions added to the README. Closing this out. Thanks!
